export const countries = {
	"AF": "Afghanistan",
	"AL": "Albania", 
	"DZ": "Algeria", 
	"AI": "Anguilla", 
	"AM": "Armenia", 
	"AW": "Aruba", 
	"AT": "Austria", 
	"BH": "Bahrain", 
	"BD": "Bangladesh", 
	"BB": "Barbados", 
	"BY": "Belarus", 
	"BE": "Belgium", 
	"BZ": "Belize", 
	"BJ": "Benin", 
	"BM": "Bermuda",
	"BT": "Bhutan", 
	"BO": "Bolivia", 
	"BA": "Bosnia and Herzegovina", 
	"BW": "Botswana", 
	"BR": "Brazil", 
	"VG": "British Virgin Islands", 
	"BN": "Brunei Darussalam", 
	"BG": "Bulgaria", 
	"BF": "Burkina Faso", 
	"BI": "Burundi", 
	"KH": "Cambodia", 
	"CM": "Cameroon", 
	"CF": "Central African Republic", 
	"TD": "Chad", 
	"CO": "Colombia", 
	"CR": "Costa Rica", 
	"HR": "Croatia", 
	"CU": "Cuba", 
	"CW": "Curaçao", 
	"CZ": "Czech Republic", 
	"CI": "Côte d'Ivoire", 
	"KP": "Dem. Rep. Korea", 
	"CD": "Democratic Republic of the Congo", 
	"DJ": "Djibouti", 
	"DM": "Dominica", 
	"DO": "Dominican Republic", 
	"EC": "Ecuador", 
	"EG": "Egypt", 
	"SV": "El Salvador", 
	"GQ": "Equatorial Guinea", 
	"ER": "Eritrea", 
	"EE": "Estonia", 
	"ET": "Ethiopia", 
	"FI": "Finland", 
	"GF": "French Guiana", 
	"GA": "Gabon", 
	"GE": "Georgia", 
	"DE": "Germany", 
	"GH": "Ghana", 
	"GL": "Greenland", 
	"GD": "Grenada", 
	"GU": "Guam", 
	"GT": "Guatemala", 
	"GN": "Guinea", 
	"GW": "Guinea-Bissau", 
	"GY": "Guyana", 
	"HT": "Haiti", 
	"HN": "Honduras", 
	"HU": "Hungary", 
	"IS": "Iceland", 
	"IN": "India", 
	"IR": "Iran", 
	"IQ": "Iraq", 
	"IE": "Ireland", 
	"IL": "Israel", 
	"JM": "Jamaica", 
	"JO": "Jordan", 
	"KZ": "Kazakhstan", 
	"KE": "Kenya", 
	"XK": "Kosovo", 
	"KW": "Kuwait", 
	"KG": "Kyrgyzstan", 
	"LA": "Lao PDR", 
	"LV": "Latvia", 
	"LB": "Lebanon", 
	"LS": "Lesotho", 
	"LR": "Liberia", 
	"LY": "Libya", 
	"LT": "Lithuania", 
	"LU": "Luxembourg", 
	"MK": "Macedonia", 
	"MG": "Madagascar", 
	"MW": "Malawi", 
	"MV": "Maldives", 
	"ML": "Mali", 
	"MH": "Marshall Islands", 
	"MQ": "Martinique", 
	"MR": "Mauritania", 
	"YT": "Mayotte", 
	"MX": "Mexico", 
	"MD": "Moldova", 
	"MN": "Mongolia", 
	"ME": "Montenegro", 
	"MS": "Montserrat", 
	"MA": "Morocco", 
	"MZ": "Mozambique", 
	"MM": "Myanmar", 
	"NA": "Namibia", 
	"NR": "Nauru", 
	"NP": "Nepal", 
	"NL": "Netherlands", 
	"BQBO": "Netherlands", 
	"NI": "Nicaragua", 
	"NE": "Niger", 
	"NG": "Nigeria", 
	"PK": "Pakistan", 
	"PW": "Palau", 
	"PS": "Palestine", 
	"PA": "Panama", 
	"PY": "Paraguay", 
	"PE": "Peru", 
	"PL": "Poland", 
	"PT": "Portugal", 
	"QA": "Qatar", 
	"CG": "Republic of Congo", 
	"KR": "Republic of Korea", 
	"RE": "Reunion", 
	"RO": "Romania", 
	"RW": "Rwanda", 
	"BQSA": "Saba (Netherlands)", 
	"LC": "Saint Lucia", 
	"VC": "Saint Vincent and the Grenadines", 
	"BL": "Saint-Barthélemy", 
	"MF": "Saint-Martin", 
	"SA": "Saudi Arabia", 
	"SN": "Senegal", 
	"RS": "Serbia", 
	"SL": "Sierra Leone", 
	"SX": "Sint Maarten", 
	"SK": "Slovakia", 
	"SI": "Slovenia", 
	"SO": "Somalia", 
	"ZA": "South Africa", 
	"SS": "South Sudan", 
	"ES": "Spain", 
	"LK": "Sri Lanka", 
	"BQSE": "St. Eustatius (Netherlands)", 
	"SD": "Sudan", 
	"SR": "Suriname", 
	"SZ": "Swaziland", 
	"SE": "Sweden", 
	"CH": "Switzerland", 
	"SY": "Syria", 
	"TW": "Taiwan", 
	"TJ": "Tajikistan", 
	"TZ": "Tanzania", 
	"TH": "Thailand", 
	"GM": "The Gambia", 
	"TL": "Timor-Leste", 
	"TG": "Togo", 
	"TN": "Tunisia", 
	"TM": "Turkmenistan", 
	"TV": "Tuvalu", 
	"UG": "Uganda", 
	"UA": "Ukraine", 
	"AE": "United Arab Emirates", 
	"UY": "Uruguay", 
	"UZ": "Uzbekistan", 
	"VE": "Venezuela", 
	"VN": "Vietnam", 
	"EH": "Western Sahara", 
	"YE": "Yemen", 
	"ZM": "Zambia", 
	"ZW": "Zimbabwe"
 }

export const countriesArray = Object.entries(countries).map(([code, name]) => ({ code, name }));


export const worldParts = {
  "Africa": [
    "DZ", "AO", "BJ", "BW", "BF", "BI", "CM", "CV", "CF", "TD", "KM", "CD", "DJ", "EG", "GQ", "ER", "ET", "GA", "GM", "GH", "GN", "GW", "CI", "KE", "LS", "LR", "LY", "MG", "MW", "ML", "MR", "MU", "YT", "MA", "MZ", "NA", "NE", "NG", "CG", "RE", "RW", "SH", "ST", "SN", "SC", "SL", "SO", "ZA", "SS", "SD", "SZ", "TZ", "TG", "TN", "UG", "EH", "ZM", "ZW"
  ],
  "Asia": [
    "AF", "AM", "AZ", "BH", "BD", "BT", "BN", "KH", "CN", "CY", "GE", "IN", "ID", "IR", "IQ", "IL", "JP", "JO", "KZ", "KP", "KR", "KW", "KG", "LA", "LB", "MY", "MV", "MN", "MM", "NP", "OM", "PK", "PS", "PH", "QA", "SA", "SG", "LK", "SY", "TW", "TJ", "TH", "TL", "TR", "TM", "AE", "UZ", "VN", "YE"
  ],
  "Europe": [
    "AL", "AD", "AT", "BY", "BE", "BA", "BG", "HR", "CY", "CZ", "DK", "EE", "FO", "FI", "FR", "DE", "GI", "GR", "HU", "IS", "IE", "IM", "IT", "XK", "LV", "LI", "LT", "LU", "MK", "MT", "MD", "MC", "ME", "NL", "NO", "PL", "PT", "RO", "RU", "SM", "RS", "SK", "SI", "ES", "SJ", "SE", "CH", "UA", "GB", "VA"
  ],
  "North America": [
    "AI", "AG", "AW", "BS", "BB", "BZ", "BM", "CA", "KY", "CR", "CU", "DM", "DO", "SV", "GL", "GD", "GP", "GT", "HT", "HN", "JM", "MQ", "MX", "MS", "NI", "PA", "PR", "BL", "KN", "LC", "MF", "PM", "VC", "SX", "TT", "TC", "US", "VG", "VI"
  ],
  "South America": [
    "AR", "BO", "BR", "CL", "CO", "EC", "FK", "GF", "GY", "PY", "PE", "SR", "UY", "VE"
  ],
  "Oceania": [
    "AS", "AU", "CK", "FJ", "PF", "GU", "KI", "MH", "FM", "NR", "NC", "NZ", "NU", "NF", "MP", "PW", "PG", "PN", "WS", "SB", "TK", "TO", "TV", "VU", "WF"
  ]
}
